# Generated by Django 2.1.7 on 2019-03-23 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_code', models.PositiveSmallIntegerField()),
                ('region_name', models.CharField(max_length=50)),
                ('dept_code', models.CharField(max_length=3)),
                ('distr_code', models.PositiveSmallIntegerField()),
                ('code', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('population', models.PositiveIntegerField()),
                ('average_age', models.FloatField()),
            ],
        ),
    ]
